#!/bin/sh

rm -f config.* src/Makedeps src/Makevars \
    src/*.o src/*.d src/*.a src/*.dll src/*.so src/*.rc */*~ *~

rm -rf -- tools/common tools/examples tools/openmpt123 tools/sounddsp libtool \
    tools/soundlib tools/test

