# Generated by cpp11: do not edit by hand

play_ <- function(mod, samplerate, progress) {
  .Call(`_openmpt_play_`, mod, samplerate, progress)
}

get_ctls_ <- function(mod) {
  .Call(`_openmpt_get_ctls_`, mod)
}

ctl_get_text_ <- function(mod, ctl) {
  .Call(`_openmpt_ctl_get_text_`, mod, ctl)
}

ctl_get_int_ <- function(mod, ctl) {
  .Call(`_openmpt_ctl_get_int_`, mod, ctl)
}

ctl_get_bool_ <- function(mod, ctl) {
  .Call(`_openmpt_ctl_get_bool_`, mod, ctl)
}

ctl_get_double_ <- function(mod, ctl) {
  .Call(`_openmpt_ctl_get_double_`, mod, ctl)
}

format_pattern_row_channel_ <- function(mod, pattern, row, channel, width, pad) {
  .Call(`_openmpt_format_pattern_row_channel_`, mod, pattern, row, channel, width, pad)
}

format_pattern_ <- function(mod, pattern, width, pad) {
  .Call(`_openmpt_format_pattern_`, mod, pattern, width, pad)
}

lompt_get_string_ <- function(key) {
  .Call(`_openmpt_lompt_get_string_`, key)
}

get_metadata_keys_ <- function(mod) {
  .Call(`_openmpt_get_metadata_keys_`, mod)
}

get_duration_seconds_ <- function(mod) {
  .Call(`_openmpt_get_duration_seconds_`, mod)
}

get_position_seconds_ <- function(mod) {
  .Call(`_openmpt_get_position_seconds_`, mod)
}

get_metadata_ <- function(mod, key) {
  .Call(`_openmpt_get_metadata_`, mod, key)
}

read_from_raw_ <- function(data) {
  .Call(`_openmpt_read_from_raw_`, data)
}

set_channel_mute_status_ <- function(mod, channel, status) {
  .Call(`_openmpt_set_channel_mute_status_`, mod, channel, status)
}

get_channel_mute_status_ <- function(mod, channel) {
  .Call(`_openmpt_get_channel_mute_status_`, mod, channel)
}

set_global_volume_ <- function(mod, volume) {
  .Call(`_openmpt_set_global_volume_`, mod, volume)
}

get_global_volume_ <- function(mod) {
  .Call(`_openmpt_get_global_volume_`, mod)
}

set_channel_volume_ <- function(mod, channel, volume) {
  .Call(`_openmpt_set_channel_volume_`, mod, channel, volume)
}

get_channel_volume_ <- function(mod, channel) {
  .Call(`_openmpt_get_channel_volume_`, mod, channel)
}

set_pitch_factor_ <- function(mod, factor) {
  .Call(`_openmpt_set_pitch_factor_`, mod, factor)
}

get_pitch_factor_ <- function(mod) {
  .Call(`_openmpt_get_pitch_factor_`, mod)
}

set_tempo_factor_ <- function(mod, factor) {
  .Call(`_openmpt_set_tempo_factor_`, mod, factor)
}

get_tempo_factor_ <- function(mod) {
  .Call(`_openmpt_get_tempo_factor_`, mod)
}

render_ <- function(mod, filename, samplerate) {
  .Call(`_openmpt_render_`, mod, filename, samplerate)
}

set_position_seconds_ <- function(mod, secs) {
  .Call(`_openmpt_set_position_seconds_`, mod, secs)
}

set_position_order_row_ <- function(mod, order, row) {
  .Call(`_openmpt_set_position_order_row_`, mod, order, row)
}
