# Generated by cpp11: do not edit by hand

test_omt_progress <- function(mod, progress) {
  .Call(`_openmpt_test_omt_progress`, mod, progress)
}

play_ <- function(mod, samplerate, progress, duration) {
  .Call(`_openmpt_play_`, mod, samplerate, progress, duration)
}

get_ctls_ <- function(mod) {
  .Call(`_openmpt_get_ctls_`, mod)
}

ctl_get_ <- function(mod, ctl) {
  .Call(`_openmpt_ctl_get_`, mod, ctl)
}

ctl_set_ <- function(mod, ctl, value) {
  .Call(`_openmpt_ctl_set_`, mod, ctl, value)
}

format_pattern_row_channel_ <- function(mod, pattern, row, channel, width, pad) {
  .Call(`_openmpt_format_pattern_row_channel_`, mod, pattern, row, channel, width, pad)
}

format_pattern_row_channel_command_ <- function(mod, pattern, row, channel, command) {
  .Call(`_openmpt_format_pattern_row_channel_command_`, mod, pattern, row, channel, command)
}

highlight_pattern_row_channel_ <- function(mod, pattern, row, channel, width, pad) {
  .Call(`_openmpt_highlight_pattern_row_channel_`, mod, pattern, row, channel, width, pad)
}

highlight_pattern_row_channel_command_ <- function(mod, pattern, row, channel, command) {
  .Call(`_openmpt_highlight_pattern_row_channel_command_`, mod, pattern, row, channel, command)
}

format_pattern_ <- function(mod, pattern, width, pad) {
  .Call(`_openmpt_format_pattern_`, mod, pattern, width, pad)
}

test_get_mod <- function(mod) {
  .Call(`_openmpt_test_get_mod`, mod)
}

has_audio_device_ <- function() {
  .Call(`_openmpt_has_audio_device_`)
}

lompt_get_string_ <- function(key) {
  .Call(`_openmpt_lompt_get_string_`, key)
}

get_metadata_keys_ <- function(mod) {
  .Call(`_openmpt_get_metadata_keys_`, mod)
}

get_duration_seconds_ <- function(mod) {
  .Call(`_openmpt_get_duration_seconds_`, mod)
}

get_position_seconds_ <- function(mod) {
  .Call(`_openmpt_get_position_seconds_`, mod)
}

get_metadata_ <- function(mod, key) {
  .Call(`_openmpt_get_metadata_`, mod, key)
}

get_num_instruments_ <- function(mod) {
  .Call(`_openmpt_get_num_instruments_`, mod)
}

get_num_samples_ <- function(mod) {
  .Call(`_openmpt_get_num_samples_`, mod)
}

get_num_channels_ <- function(mod) {
  .Call(`_openmpt_get_num_channels_`, mod)
}

get_num_orders_ <- function(mod) {
  .Call(`_openmpt_get_num_orders_`, mod)
}

get_num_patterns_ <- function(mod) {
  .Call(`_openmpt_get_num_patterns_`, mod)
}

get_num_subsongs_ <- function(mod) {
  .Call(`_openmpt_get_num_subsongs_`, mod)
}

get_pattern_num_rows_ <- function(mod, pattern) {
  .Call(`_openmpt_get_pattern_num_rows_`, mod, pattern)
}

get_order_pattern_ <- function(mod, order) {
  .Call(`_openmpt_get_order_pattern_`, mod, order)
}

read_from_raw_ <- function(data) {
  .Call(`_openmpt_read_from_raw_`, data)
}

set_channel_mute_status_ <- function(mod, channel, status) {
  .Call(`_openmpt_set_channel_mute_status_`, mod, channel, status)
}

get_channel_mute_status_ <- function(mod, channel) {
  .Call(`_openmpt_get_channel_mute_status_`, mod, channel)
}

set_global_volume_ <- function(mod, volume) {
  .Call(`_openmpt_set_global_volume_`, mod, volume)
}

get_global_volume_ <- function(mod) {
  .Call(`_openmpt_get_global_volume_`, mod)
}

set_channel_volume_ <- function(mod, channel, volume) {
  .Call(`_openmpt_set_channel_volume_`, mod, channel, volume)
}

get_channel_volume_ <- function(mod, channel) {
  .Call(`_openmpt_get_channel_volume_`, mod, channel)
}

set_pitch_factor_ <- function(mod, factor) {
  .Call(`_openmpt_set_pitch_factor_`, mod, factor)
}

get_pitch_factor_ <- function(mod) {
  .Call(`_openmpt_get_pitch_factor_`, mod)
}

set_tempo_factor_ <- function(mod, factor) {
  .Call(`_openmpt_set_tempo_factor_`, mod, factor)
}

get_tempo_factor_ <- function(mod) {
  .Call(`_openmpt_get_tempo_factor_`, mod)
}

get_instrument_names_ <- function(mod) {
  .Call(`_openmpt_get_instrument_names_`, mod)
}

get_sample_names_ <- function(mod) {
  .Call(`_openmpt_get_sample_names_`, mod)
}

get_channel_names_ <- function(mod) {
  .Call(`_openmpt_get_channel_names_`, mod)
}

get_pattern_names_ <- function(mod) {
  .Call(`_openmpt_get_pattern_names_`, mod)
}

get_subsong_names_ <- function(mod) {
  .Call(`_openmpt_get_subsong_names_`, mod)
}

get_order_names_ <- function(mod) {
  .Call(`_openmpt_get_order_names_`, mod)
}

render_ <- function(mod, filename, samplerate, duration) {
  .Call(`_openmpt_render_`, mod, filename, samplerate, duration)
}

get_render_param_ <- function(mod, param) {
  .Call(`_openmpt_get_render_param_`, mod, param)
}

set_render_param_ <- function(mod, param, value) {
  .Call(`_openmpt_set_render_param_`, mod, param, value)
}

get_repeat_count_ <- function(mod) {
  .Call(`_openmpt_get_repeat_count_`, mod)
}

set_repeat_count_ <- function(mod, repeat_count) {
  .Call(`_openmpt_set_repeat_count_`, mod, repeat_count)
}

set_position_seconds_ <- function(mod, secs) {
  .Call(`_openmpt_set_position_seconds_`, mod, secs)
}

set_position_order_row_ <- function(mod, order, row) {
  .Call(`_openmpt_set_position_order_row_`, mod, order, row)
}

get_current_channel_vu_left_ <- function(mod, channel) {
  .Call(`_openmpt_get_current_channel_vu_left_`, mod, channel)
}

get_current_channel_vu_mono_ <- function(mod, channel) {
  .Call(`_openmpt_get_current_channel_vu_mono_`, mod, channel)
}

get_current_channel_vu_right_ <- function(mod, channel) {
  .Call(`_openmpt_get_current_channel_vu_right_`, mod, channel)
}

get_current_channel_vu_rear_left_ <- function(mod, channel) {
  .Call(`_openmpt_get_current_channel_vu_rear_left_`, mod, channel)
}

get_current_channel_vu_rear_right_ <- function(mod, channel) {
  .Call(`_openmpt_get_current_channel_vu_rear_right_`, mod, channel)
}

get_current_estimated_bpm_ <- function(mod) {
  .Call(`_openmpt_get_current_estimated_bpm_`, mod)
}

get_current_order_ <- function(mod) {
  .Call(`_openmpt_get_current_order_`, mod)
}

get_current_pattern_ <- function(mod) {
  .Call(`_openmpt_get_current_pattern_`, mod)
}

get_current_playing_channels_ <- function(mod) {
  .Call(`_openmpt_get_current_playing_channels_`, mod)
}

get_current_row_ <- function(mod) {
  .Call(`_openmpt_get_current_row_`, mod)
}

get_current_speed_ <- function(mod) {
  .Call(`_openmpt_get_current_speed_`, mod)
}

get_current_tempo_ <- function(mod) {
  .Call(`_openmpt_get_current_tempo_`, mod)
}

get_selected_subsong_ <- function(mod) {
  .Call(`_openmpt_get_selected_subsong_`, mod)
}

select_subsong_ <- function(mod, subsong) {
  .Call(`_openmpt_select_subsong_`, mod, subsong)
}
